### ISSUE TITLE
Implement model & controller for Topics (listing) page

### ISSUE THREAD

**Issue by pmuir** [strimzi/strimzi-ui#124]
Implement the model & controller for the Topics (listing) page. #70 contains the designs. See also #123 and #122 for the view implementations.

**Comment by matthew-chirgwin** [comment]
For the first stage, I am hoping this will be a simple model hook, calling a `useQuery` to get the data/deal with loading/errors etc. 

I expect while this will be quite boilerplate like for now, other functions etc will follow/be added to this model
