### ISSUE TITLE
Implement Patternfly / Carbon view build time switching.

### ISSUE THREAD

**Issue by dlabaj** [strimzi/strimzi-ui#127]
Carbon and PatternFly build time switching should be implemented to allow the team build either view for strimzi-ui.

**Comment by matthew-chirgwin** [comment]
Isn't this implemented (and integrated)? https://github.com/strimzi/strimzi-ui/blob/4a5d063b0a894541eed60c2de716e17467db5007/build/webpack.common.js#L61
