### ISSUE TITLE
Pattern for extending RTL functionality. E.g. creating `withX` functions that get passed to `render`.

### ISSUE THREAD

**Issue by matthew-chirgwin** [strimzi/strimzi-ui#138]
Content to follow

**Comment by JQrdan** [comment]
The aim with this is to create a test utility that converts RTL render into a builder pattern. Allowing us to chain together wrapping utilities without it becoming a mess. For example: 

```
const renderResult = myComponent.withRouter().withConfigProvider().render();
```
