### ISSUE TITLE
Use HTTP over Websockets

### ISSUE THREAD

**Issue by matthew-chirgwin** [strimzi/strimzi-ui#142]
Issue to update the UI to use HTTP (vs Websockets) for data fetching.

Websockets enable GQL subscriptions, where as HTTP does not. However, using server side events, HTTP can be used with a few changes on the client/server.

This issue is to investigate/implement the required changes.

**Comment by wtrocki** [comment]
Would subscriptions be used to consuming topic information or something else as well?

**Comment by matthew-chirgwin** [comment]
@wtrocki topics is just the start. In due course (as designs/UX are worked on) I am anticipating the need for 'live' data for more than just topics

@pmuir - I should have asked this yesterday but it slipped my mind. Is it just 'strimzi-admin' websocket traffic which would be an issue, or all websocket traffic? I ask as currently our logging capability uses a websocket from client to server to send logging events

**Comment by pmuir** [comment]
It's particularly the react frontend -> strimzi-ui server that is an issue.

We would be fine with degrading the UI to not send logging.

**Comment by wtrocki** [comment]
https://wundergraph.com/blog/deprecate_graphql_subscriptions_over_websockets

Good read
