### ISSUE TITLE
UI mockups /screenshots

### ISSUE THREAD

**Issue by kasriniv** [strimzi/strimzi-ui#17]
It will be great to see some screenshots of what is being developed. If not those, even UI mockups will be great to see on the readme.

**Comment by matthew-chirgwin** [comment]
Hi @kasriniv! There is a mock up of what a 'Topics' page may look like in the proposal if you havent seen it already: https://github.com/matthew-chirgwin/proposals/blob/ui-proposal/009-strimzi-ui.md . Once all the foundational/infrastructure type work is sorted, and proposals agreed, I am hoping we will have issues for the various UI screens and add mockups/designs as a part of those issues.

**Comment by chgl** [comment]
Hi @matthew-chirgwin, before polluting the issues unnecessarily I thought I might just ask in this tangentially related issue :)

> Once all the foundational/infrastructure type work is sorted, and proposals agreed, I am hoping we will have issues for the various UI screens and add mockups/designs as a part of those issues.

Do you already accept such issues with feature requests? Things like:

* Ability to reset consumer groups
* Ability to delete topics
* Cluster visualization
* ...

if so, then I could go ahead and create them.

**Comment by matthew-chirgwin** [comment]
Hi @chgl ! I see no harm in raising them now. As mentioned in the proposal, there are a set of screens and capabilities we will be implementing first, starting with a topics listing page (with the ability to create/delete following for example). After that however, others could be added, with agreement from the @strimzi/maintainers . I think raising the issues, and starting discussions early is not a bad idea.
