### ISSUE TITLE
Use Typescript over Javascript

### ISSUE THREAD

**Issue by matthew-chirgwin** [strimzi/strimzi-ui#19]
Recent discussions have mentioned the use of Typescript over Javascript. This issue is to track that discussion, best practise, and actions to update the proposal/repo based on those discussions.

**Comment by scholzj** [comment]
My private preference would probably be Javascript ... But if the people planning to work on the UI like your self prefer TypeScript you should go for it.

**Comment by matthew-chirgwin** [comment]
Hi @scholzj . We have been discussing using TS over JS for the Strimzi-ui with @dlabaj for the last few weeks. It will bring a number of benefits to the Strimzi UI (keeping view layers in step, spotting bugs early, enforcing structure etc), and in some places makes the code more Java like. @dlabaj is familiar/has some reccomendations he will share.

I am just about to update the UI proposal mentioning this - more than happy to discuss further there (or here - whatever works for you).

**Comment by scholzj** [comment]
As I said ... if you prefer TS, you should definitely go with it. I don't have problem with it.
