### ISSUE TITLE
Translation tooling/approach

### ISSUE THREAD

**Issue by matthew-chirgwin** [strimzi/strimzi-ui#21]
The UI should be fully translatable from day 0. This issue is to look into either writing our own translation tooling or using a 3rd party library, and writing supporting documentation to how it works/should be used across the Strimzi-ui

**Comment by dlabaj** [comment]
Most of the projects I have worked on have used https://www.i18next.com/. There's also are react implementation that is optional https://react.i18next.com/.  Worth a look.

**Comment by nictownsend** [comment]
Current concerns over i18next are around the HTML formatted strings:

```
<Trans i18nKey="userMessagesUnread" count={count}>
      Hello <strong title={t('nameTitle')}>{{name}}</strong>, you have {{count}} unread message. <Link to="/msgs">Go to messages</Link>.
    </Trans>
```

```
"userMessagesUnread": "Hello <1>{{name}}</1>, you have {{count}} unread message. <5>Go to message</5>.",
"userMessagesUnread_plural": "Hello <1>{{name}}</1>, you have {{count}} unread messages.  <5>Go to messages</5>.",
```

In particular - `<5>` is based off knowing how React renders the contents of the `<Trans>` - it's the 5th element in the render tree.

Continuing to evaluate the rest of it vs other libraries

**Comment by matthew-chirgwin** [comment]
And just FYI @dlabaj , we came up with https://github.com/ibm-messaging/kafka-java-vertx-starter/tree/master/ui/src/ReactCustomHooks/useTranslate to address @nictownsend 's point for a previous UI. Its there if we think it might help/be of use, but I am sure there are much more mature 3rd party tools available.
