### ISSUE TITLE
Update commitlint to version 11.0.0

### ISSUE THREAD

**Issue by JQrdan** [strimzi/strimzi-ui#23]
We currently use version 9.1.0 which has a bug where it can't correctly identify if a commit includes a `Signed-off-by` line at the end of the commit. 

This has now been fixed through this issue https://github.com/conventional-changelog/commitlint/issues/1809

Version 11.0.0 is currently the latest version and also includes this fix

**Comment by matthew-chirgwin** [comment]
Once updated, I would also update the 'known issues' in the readme/other places we reference the commitlint tool to remove mention of this issue.
