### ISSUE TITLE
Introspection Context

### ISSUE THREAD

**Issue by matthew-chirgwin** [strimzi/strimzi-ui#39]
Issue to implement an Introspection Context, as described in https://github.com/strimzi/strimzi-ui/blob/master/docs/Architecture.md#introspection and https://github.com/strimzi/strimzi-ui/tree/master/client/Contexts/Introspect

- Requires GQL library ( #38 ), testing issues to be completed

**Comment by pmuir** [comment]
I'll take this one - I don't have permissions to assign etc.

**Comment by matthew-chirgwin** [comment]
> I'll take this one - I don't have permissions to assign etc.

@scholzj would you be able to add @pmuir to the Strimzi-ui devs group?

**Comment by scholzj** [comment]
@pmuir You should have an invite in your mail.
