### ISSUE TITLE
Architecture (post proposal): Security

### ISSUE THREAD

**Issue by matthew-chirgwin** [strimzi/strimzi-ui#44]
To discuss/define:

- How authentication, authorization and sessions are handled in the UI
- CRUD model mentioned in https://github.com/strimzi/strimzi-ui/issues/12#issuecomment-679206635 and how this maps to authorization/roles

**Comment by nictownsend** [comment]
Documentation delivered. Will raise additional issue (and an epic) for the follow on pieces.
