### ISSUE TITLE
Navigation Component

### ISSUE THREAD

**Issue by matthew-chirgwin** [strimzi/strimzi-ui#68]
Issue to implement the Navigation Bootstrap component described in https://github.com/strimzi/strimzi-ui/blob/master/docs/Architecture.md#routing-and-navigation / https://github.com/strimzi/strimzi-ui/blob/master/client/Bootstrap/Navigation/README.md

- Requires Introspection, Feature flagging and testing issues to be completed

**Comment by JQrdan** [comment]
This most certainly has seen activity
