### ISSUE TITLE
Update/Remove git commit hash from end of gh-actions comment 

### ISSUE THREAD

**Issue by JQrdan** [strimzi/strimzi-ui#71]
Now that the workflow trigger has changed to `pull_request_target`, the commit that triggered the workflow is [the commit to enable the comment to work](https://github.com/strimzi/strimzi-ui/commit/5e4c7fdd3ed626bd37d293e56a7bc29fb940617e). So, this needs to be updated to show the PR commit that triggered the workflow if possible and removed if not.

**Comment by matthew-chirgwin** [comment]
Is this still true @JQrdan ?

**Comment by JQrdan** [comment]
@matthew-chirgwin Yep! Haven't had a chance to sort this one yet, will put that next on my list
