### ISSUE TITLE
Login UX

### ISSUE THREAD

**Issue by matthew-chirgwin** [strimzi/strimzi-ui#86]
Issue to cover the discussion and development of UX around Login (https://github.com/strimzi/proposals/blob/master/010-ui-and-admin-server-security.md)

-  For no security or Oauth based flows no screen will need to be presented as it will be handled externally/not needed. However, some UX to confirm this may be worth exploring
-  For Scram based logins, a username and password (with error states)

As a part of the discussion, the defintion of a set of Gherkin based behaviours should be identified, which will be used as the base for acceptance testing.

This discussion may also identify other UI components required to enable these flows. These should be discussed/designed in their own issues.

**Comment by matthew-chirgwin** [comment]
One point mentioned by @pmuir in today's sync: In the case of an oauth flow, a redirect will occur to the Oauth login page, and once complete, the user would be redirected back. Worth capturing in any behavioural write ups

**Comment by chloepoulterdesign** [comment]
Some quick thoughts about the "default" option I'd probably expect us to run with.
Examples included of basic client-side error (someone hits "Log in" before completing both fields) and server side error (invalid username or password).
![image](https://user-images.githubusercontent.com/47979346/98796311-25a4ef00-2403-11eb-8138-e5eee0913cf6.png)

I'm not clear whether there is a use-case for the "Log in with Oauth" link I've included yet - presumably if Oauth is the correct method, we'll always successfully redirect users on log-in, however, I know it's a common pattern to offer alternative log in methods on a log in page and have included it for discussion purposes. 

Note that these designs are subject to change and are here to provoke conversation & make sure we get the experience right.

**Comment by matthew-chirgwin** [comment]
> Some quick thoughts about the "default" option I'd probably expect us to run with.
> Examples included of basic client-side error (someone hits "Log in" before completing both fields) and server side error (invalid username or password).
> ![image](https://user-images.githubusercontent.com/47979346/98796311-25a4ef00-2403-11eb-8138-e5eee0913cf6.png)
> 
> I'm not clear whether there is a use-case for the "Log in with Oauth" link I've included yet - presumably if Oauth is the correct method, we'll always successfully redirect users on log-in, however, I know it's a common pattern to offer alternative log in methods on a log in page and have included it for discussion purposes.
> 
> Note that these designs are subject to change and are here to provoke conversation & make sure we get the experience right.

Looks good, thanks @chloepoulterdesign ! Re the login with OAuth - I imagine you would only ever see this login page if credentials need to be provided by the user (ie the Scram case). The authentication mechanism used is not a choice the user makes - it is whoever deploys the UI in Strimzi's. Thus, I don't think there should be a link here at all. 

That isnt to say however as a part of the UI processing the login we mention 'redirecting to OAuth provider'/' logged in via OAuth' or similar somehere, if that enhances/improves the UX.

**Comment by lboehling** [comment]
PF Login page designs: 

_Default_

- I've kept some additional functionality in these designs to see if any can/should be added. Specifically curious about the ability to stay logged in, log in via social sign-in methods, and to create an account/signup. 

![Simple](https://user-images.githubusercontent.com/46571616/99849563-c608bb00-2b49-11eb-9b59-e08dfcd03b80.png)

_On submit_
![Submit with loade](https://user-images.githubusercontent.com/46571616/99849567-c739e800-2b49-11eb-8223-c398ed7ec2fe.png)

_Client Side Error_
![Client Error](https://user-images.githubusercontent.com/46571616/99849555-c5702480-2b49-11eb-9c7c-33dacff810f5.png)

_Server Side Error_
![Server Error](https://user-images.githubusercontent.com/46571616/99849559-c5702480-2b49-11eb-938a-0861d7609ada.png)

**Comment by chloepoulterdesign** [comment]
Very snazzy @lboehling .

I'll let the devs answer your questions on social, staying logged in, and create account. I suspect you can't do any of these with the SCRAM method, and when logged in via keycloak, that would all be handled on their UI?

The only updates at my end are removal of the Oauth option and I am 90% sure the recommended carbon loading state for a momentary (less than 3 second) loading state would be an inline loading state, which I've included.

![image](https://user-images.githubusercontent.com/47979346/99967376-b24e9600-2d8f-11eb-8814-93601c6e31f1.png)
![image](https://user-images.githubusercontent.com/47979346/99967393-b975a400-2d8f-11eb-9102-ca723cf6f7e3.png)
![image](https://user-images.githubusercontent.com/47979346/99967623-09546b00-2d90-11eb-8c3a-8bcedffaa34b.png)


To give an idea of snazzier options we could go down via carbon, you can also view the [Carbon Login pattern](https://www.carbondesignsystem.com/patterns/login-pattern) - however I feel that they're kind of overkill for what is needed here. Plus, the pattern used here is one I'm familiar with.

**Comment by chloepoulterdesign** [comment]
I've just heard we'll need original illustration/imagery for the log in page. I'm chasing it up and will have something sorted asap.

**Comment by matthew-chirgwin** [comment]
Thanks both, these look great!

>   * I've kept some additional functionality in these designs to see if any can/should be added. Specifically curious about the ability to stay logged in, log in via social sign-in methods, and to create an account/signup.

We will be authenticating with Kafka (scram), or something configured by the user (eg KeyCloak) when deploying their cluster to handle the authentication (OAuth). I know a bunch of social sites offer OAuth options, but I have no idea if any could be then used (and work) with Strimzi (nor would anyone actually try). It may be possible, but I would suggest that we return to those options at a later stage.

I would also suggest allowing a user to sign up/trigger a password reset through the login page is the responsibility of the provider of the authentication - ie KeyCloak etc.

**Comment by pmuir** [comment]
Keycloak supports social login, identity federation etc. so if you configure oauth login then you should get social login if you configure it correctly in Keycloak. Those screens are provided by keycloak.

**Comment by pmuir** [comment]
@lboehling If you are using Scram then social login won't be possible - you need to use oauth for that.

We could create users and allow managing users via the UI for SCRAM but I think we can defer that for a long time - if you want that kind of functionality you should use oauth/keycloak.
For now you would use the Strimzi CLI https://strimzi.io/docs/0.12.1/#assembly-getting-started-user-operator-str

Staying logged in is really an attribute of the session length we decide to offer and something we could make configurable. However a shorter session is better for security.

Note that if you are using keycloak then our session length is somewhat irrelevant, this is up to keycloak.

**Comment by pmuir** [comment]
@lboehling I think we are good to go on this one. Do you agree?
