### ISSUE TITLE
UI Bootstrap UX

### ISSUE THREAD

**Issue by matthew-chirgwin** [strimzi/strimzi-ui#87]
Issue to cover the discussion and development of UX of the timeframe where the UI bootstraps itself.

From a UX POV, we will need to cover/handle the loading (and error states) of three data requests/result handling. These requests will be for:

- Authorization status (if security enabled)
- Introspection (to discover backend capability)
- Configuration

In a golden path scenario, I imagine this will be a loading spinner (or similar) while the data is fetched/processed. I would expect all 3 calls to be excuted in paralell, and be reasonibly quick to complete.

What I am unsure of is how an error would be surfaced, and if a retry button (for example) would be of use.

As a part of the discussion, the defintion of a set of Gherkin based behaviours should be identified, which will be used as the base for acceptance testing.

This discussion may also identify other UI components required to enable these flows. These should be discussed/designed in their own issues.

**Comment by chloepoulterdesign** [comment]
Hey @matthew-chirgwin is this for any particular user action, i.e. logging in, or is this on any given UI action?

Carbon has very well-written loading guidance available here: https://www.carbondesignsystem.com/patterns/loading-pattern

It talks through when full page spinners should be used, vs skeleton states.
The basic statement is - **the full page load with darkened overlay and spinner is the default.** 
![image](https://user-images.githubusercontent.com/47979346/99983692-167b5500-2da4-11eb-9d83-55205791c206.png)
Then, *if* a page takes a while, use progressive techniques like skeleton states.
![image](https://user-images.githubusercontent.com/47979346/99983784-327ef680-2da4-11eb-9f67-6086f95b9323.png)

**Comment by matthew-chirgwin** [comment]
> Hey @matthew-chirgwin is this for any particular user action, i.e. logging in, or is this on any given UI action?

Sorry, just saw this! This is a one time load, when the user first loads the UI up. There are several things going on under the covers, all of which I would suggest a full page spinner (like the one in the top screenshot) would cover. One thing I am interested to get views on is when some of the under covers work fails -  as this pretty much means the UI will be missing critical info in order to function. I assume an error message/retry buttons would help, but there would not be a lot a user could do potentially.

**Comment by chloepoulterdesign** [comment]
yeah that's an interesting one - I would probably suggest using the 404 HTTP error page - which has a "back to topics" link in it - which I would effectively see behaving as a refresh, at least while topics is the only page.

**Comment by pmuir** [comment]
If something internal fails then I would suggest a 500 (internal server error) rather than a 404 (not found) error page.

For Patternfly @lboehling can confirm, but normally we do something similar with a spinner inside the content area. Skeletons are used once we know the shape of the data.

**Comment by chloepoulterdesign** [comment]
I can put together a 500 error page very easily - it will follow the same structure as the error pages I've specced in #88
