### ISSUE TITLE
Navigation UX

### ISSUE THREAD

**Issue by matthew-chirgwin** [strimzi/strimzi-ui#90]
This issue is to cover the discussion and design of the UX of the Navigation for the Strimzi UI.

The technical exploration of how the Navigation would work can be found here (for reference): https://github.com/strimzi/strimzi-ui/tree/master/client/Bootstrap/Navigation

This write up mentions:

> In addition to this, the Navigation component is also responsible for rendering the visual Navigation components that an end user interacts with, such as the 1st, 2nd or 3rd levels of navigation. It renders these as needed, based on the current page a user is viewing, and the type of page it defines itself as. These page types are declarative to encapsulate the different types of Navigation visual components used, and are defined and exported as a part of this component.

This issue is for defining what that visual rendering is.

As a part of the discussion, the defintion of a set of Gherkin based behaviours should be identified, which will be used as the base for acceptance testing.

This discussion may also identify other UI components required to enable these flows. These should be discussed/designed in their own issues.

**Comment by matthew-chirgwin** [comment]
One thing worth mentioning at this stage:

> One question I would raise for this first stage of the Strimzi UI is the need/requirement of a visual rendering of a Navigation component (the left bar in the screenshot). Functionally the navigation will need to exist, but with one page, is there any merit in working on the visuals for one?

from: https://github.com/strimzi/strimzi-ui/issues/70#issuecomment-719586178

The visual UX still of course needs to be done - but would it make sense on just one page to have any?

**Comment by chloepoulterdesign** [comment]
I've done some early mockups to explore navigation.
My personal belief is we should implement a single navigation item so that extending it will be easier in future. 

![image](https://user-images.githubusercontent.com/47979346/99981508-63a9f780-2da1-11eb-89e2-f2682df04721.png)

**Comment by chloepoulterdesign** [comment]
Note that in https://github.com/strimzi/strimzi-ui/issues/70#issuecomment-725390948 I've suggested we employ table headers to title tables. We would need to decide whether page headers are also necessary (both likely to read "topics") or not.

**Comment by matthew-chirgwin** [comment]
> Note that in [#70 (comment)](https://github.com/strimzi/strimzi-ui/issues/70#issuecomment-725390948) I've suggested we employ table headers to title tables. We would need to decide whether page headers are also necessary (both likely to read "topics") or not.

This might be a Carbon thing - but if a page did not have a table, would a table header still be used? Or would something that looks like a table header make sense?

**Comment by chloepoulterdesign** [comment]
Very good question - I expect the guidance is written assuming that pages don't just contain one single table 😂
Can go back to your example with page title and no table header easily enough

**Comment by lboehling** [comment]
PF equivalent mockups below. Typically PF defaults to the expanded left nav, but since only one page will be present, I'd suggest defaulting to the collapsed left nav. 

![image](https://user-images.githubusercontent.com/46571616/99848796-6b229400-2b48-11eb-93a9-5e64ac7fd106.png)
