### ISSUE TITLE
Configure kafka bootstrap

### ISSUE THREAD

**Issue by dicolasi** [strimzi/strimzi-ui#98]
Hi all,
 I have a strimzi-kafka cluster running in k8n. I would like to use this ui, but from the Readme it is not clear to me how to use it. 
For instance, how do I configure the bootstrap server? 

Thanks in advance
Simone

**Comment by JQrdan** [comment]
Hi Simone,

This UI is still very early on in its development and is currently not in a state where it can be used with Strimzi yet. It's good to see that you're interested in the UI though! 😄

**Comment by dicolasi** [comment]
I see :) Thanks a lot @JQrdan. 
Have you got a timeline for this? In the meantime I am using akhq.

**Comment by JQrdan** [comment]
> Have you got a timeline for this? In the meantime I am using akhq.

Unfortunately, there's no timeline for when this would be usable. We're aiming to have an MVP with a page that shows a topic list completed very soon. There's still a lot of building block work that's going on.
